const all_players = [
  "LeBron James",
  "Kevin Durant",
  "Giannis Antetokounmpo",
  "Stephen Curry",
  "Kawhi Leonard",
  "Anthony Davis",
  "James Harden",
  "Luka Dončić",
  "Joel Embiid",
  "Nikola Jokić",
  "Damian Lillard",
  "Kyrie Irving",
  "Jimmy Butler",
  "Russell Westbrook",
  "Paul George",
  "Karl-Anthony Towns",
  "Jayson Tatum",
  "Devin Booker",
  "Bradley Beal",
  "Donovan Mitchell",
  "Chris Paul",
  "Ben Simmons",
  "Trae Young",
  "Klay Thompson",
  "Zach LaVine",
  "De'Aaron Fox",
  "Brandon Ingram",
  "Jamal Murray",
  "Jaylen Brown",
  "Domantas Sabonis",
  "Deandre Ayton",
  "CJ McCollum",
  "Kristaps Porziņģis",
  "D'Angelo Russell",
  "Shai Gilgeous-Alexander",
  "Jrue Holiday",
  "John Collins",
  "DeMar DeRozan",
  "Draymond Green",
  "Pascal Siakam",
  "Rudy Gobert",
  "Gordon Hayward",
  "Julius Randle",
  "Lonzo Ball",
  "Myles Turner",
  "Jaren Jackson Jr.",
  "Tobias Harris",
  "Kyle Lowry",
  "Malcolm Brogdon",
  "Bam Adebayo",
  "LaMelo Ball",
  "Fred VanVleet",
  "Jerami Grant",
  "Andre Drummond",
  "Dennis Schröder",
  "Michael Porter Jr.",
  "Montrezl Harrell",
  "Serge Ibaka",
  "Christian Wood",
  "Collin Sexton",
  "Khris Middleton",
  "Jusuf Nurkić",
  "Jonas Valančiūnas",
  "John Wall",
  "Andrew Wiggins",
  "Victor Oladipo",
  "Jarrett Allen",
  "Robert Covington",
  "Tyrese Haliburton",
  "Nikola Vučević",
  "Fred Hoiberg",
  "OG Anunoby",
  "Tyler Herro",
  "Derrick Rose",
  "Clint Capela",
  "Luguentz Dort",
  "Gary Trent Jr.",
  "RJ Barrett",
  "Davis Bertans",
  "Kelly Oubre Jr.",
  "Dejounte Murray",
  "Bojan Bogdanović",
  "Kevin Love",
  "Ricky Rubio",
  "Mikal Bridges",
  "Duncan Robinson",
  "Derrick White",
  "Aaron Gordon",
  "Dāvis Bertāns",
  "Dorian Finney-Smith",
  "Danilo Gallinari",
  "Joe Ingles",
  "Coby White",
  "Josh Richardson",
  "Jalen Suggs",
  "Will Barton",
  "Carmelo Anthony",
];


export const stats_type = [
  { label: 'All', value: '/all' },
  { label: 'Points', value: '/pts' },
  { label: 'Rebounds', value: '/reb' },
  { label: 'Assists', value: '/ast' },
];

export default all_players